### ISSUE TITLE
need to check if sudo is installed

### ISSUE THREAD

**Issue by craigcomstock** [nickanderson/cfengine-inventory-sudoers#3]
I noticed on a new system without `sudo` installed that this policy is quite noisy:

```
   error: execresult '/usr/bin/sudo -l -U gnats' is assumed to be executable but isn't
   error: Proposed executable file '/usr/bin/sudo' doesn't exist
```

for each user in `/etc/passwd`.

Maybe define a class if sudo is present and guard the promise with that?

https://github.com/nickanderson/cfengine-inventory-sudoers/blob/main/policy/main.cf#L76-L83

**Comment by nickanderson** [comment]
Mmmm. Yes, indeed improvements would be good here.

Looking at the MPF [I see](https://github.com/cfengine/masterfiles/blob/6604195000a67f588e72d2540508545b2367dba9/lib/paths.cf#L442) that the path for `sudo` is only defined in the context of `darwin::`. So, kinda think that I will publish the path for `sudo` and then use from paths if possible.

```cfengine3
bundle agent __main__
{
  vars:
    # Initially I was thinking to do this:
    "path[sudo]"
      string => "/usr/bin/sudo",
      if => and( fileexists( "/usr/bin/sudo" ),
                 not( "_stdlib_path_exists_sudo" )),
      meta => { "paths.cf" };

    # But, then again, that's more invasive than doing this:
    "bin_sudo"
      string => ifelse( isvariable( "default:paths.sudo" ), "$(paths.sudo)",
                        "/usr/bin/sudo" ),
      if => isexecutable( "/usr/bin/sudo" );

  reports:
    (inform_mode|verbose_mode|debug_mode).!windows::
      "Warning: Path to sudo unknown, not updating inventory"
        unless => isvariable( "bin_sudo" );

}
```

**Comment by nickanderson** [comment]
@craigcomstock can you test this: https://github.com/nickanderson/cfengine-inventory-sudoers/pull/4
